export HOMEBREW_PREFIX="/opt/homebrew"
export PATH=$HOMEBREW_PREFIX/bin:/Users/dwl/Library/Python/3.9/bin:$PATH
export PATH="$HOME/scripts":$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" # This loads nvm
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="eastwood"

plugins=(git)

source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"
